name: hola-mundo

on: 
  push:
    branches:
      - esa-no-existe #pour bypasser

jobs:
  hola-mundo-job:
    
    runs-on: ubuntu-latest

    steps:
      - name: check out repo codigo
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
