name: hola-mundo

on: push

jobs:
  hola-mundo-job:
    
    runs-on: ubuntu-latest

    steps:
      - name: check out repo codigo
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
